name: main_repository
description: Dart package which manages the app data.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.3
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0
  rxdart: ^0.22.0
  

